### PR TITLE
Fixed disabling cache (#53)

### PR DESCRIPTION
**Pull request by andrey-helldar**
See #53 issue.

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@barryvdh, are you alive?

**Comment by barryvdh** [comment]
Yeah, not really sure about this. What issue do you encounter?

**Comment by andrey-helldar** [comment]
Disabling the cache does not work (#53)

**Comment by andrey-helldar** [comment]
@barryvdh, Thank you very much!
I closed the issue 👍

**Pull request merged**
