### PR TITLE
Use isMethodCacheable instead of isMethodSafe

### PR DESCRIPTION
**Pull request by boonstoppel**
https://github.com/barryvdh/laravel-httpcache/issues/48

### CODE REVIEW

**Comment by barryvdh** [comment]
Can you re-open this?

**Comment by boonstoppel** [comment]
I submitted a new pull request:
https://github.com/barryvdh/laravel-httpcache/pull/51

**Comment by barryvdh** [comment]
Yeah I saw, but I like this better :)

**Comment by boonstoppel** [comment]
hm, git won't allow me to re-open this. I will edit the 2nd pull request.

**Comment by boonstoppel** [comment]
you closed that one. Probably easier to just submit the change yourself then.

**Pull request closed without merging**
