### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 10.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/barryvdh/laravel-httpcache/pull/60/commits/888326c0291bdeff569cdc3221e3217dc45f319c?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-httpcache.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "barryvdh/laravel-httpcache": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by barryvdh** [comment]
Thanks, replaced it with a simpler matrix though; https://github.com/barryvdh/laravel-httpcache/pull/61

**Comment by jasonmccreary** [comment]
Looks like you removed support for Laravel 6 and 7. Nice. Just not something this automation would do directly as that's the maintainers choice.

**Comment by barryvdh** [comment]
Yeah the matrix was a bit funky already, and wanted to add php 8.2
Also tests failed because phpunit required to migrate the config. Maybe that would be an easy fix for the automated upgrade?

**Comment by barryvdh** [comment]
But thanks for this and the other PR's though!

**Pull request closed without merging**
